/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->Operacion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Numero1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->Numero2))
		 return FALSE;
	return TRUE;
}
