/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	char Operacion;
	int Numero1;
	int Numero2;
};
typedef struct inputs inputs;

#define CALCULADORA_PROG 0x31111111
#define CALCULADORA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  int * suma_1(inputs *, CLIENT *);
extern  int * suma_1_svc(inputs *, struct svc_req *);
#define RESTA 2
extern  int * resta_1(inputs *, CLIENT *);
extern  int * resta_1_svc(inputs *, struct svc_req *);
#define DIVISION 3
extern  int * division_1(inputs *, CLIENT *);
extern  int * division_1_svc(inputs *, struct svc_req *);
#define MULTIPLI 4
extern  int * multipli_1(inputs *, CLIENT *);
extern  int * multipli_1_svc(inputs *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define RESTA 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define DIVISION 3
extern  int * division_1();
extern  int * division_1_svc();
#define MULTIPLI 4
extern  int * multipli_1();
extern  int * multipli_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
